name: MP02 - Terraform secure CI

on:
    pull_request: 
        branches: 
            - main
        paths:
            - "MP02 Secure IaC CI/**"
            - ".github/workflows/mp02-terraform-ci.yml"
    
    workflow_dispatch: 
    

permissions: 
    contents: read
    id-token: write

