name: MP02 - Terraform secure CI
on:
    pull_request: 
        branches: 
            - main
        paths:
            - "MP02 Secure IaC CI/**"
            - ".github/workflows/mp02-terraform-ci.yml"
    
    workflow_dispatch: 
    

permissions: 
    contents: read
    id-token: write
jobs:
    terraform-ci:
        name: terraform validate and plan 
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: "MP02 Secure IaC CI/terraform"
        steps:
            - name: checkout the code
              uses: actions/checkout@v7
            - name: setup terraform
              uses: hashicorp/setup-terraform@v4.0.1
              with: 
                terraform_version: 1.15.8
            - name: terraform format check 
              run: terraform fmt -check -recursive

            - name: terraform init
              run: terraform init -input=false -lockfile=readonly
            
            - name: terraform validate
              run: terraform validate -no-color
            
            - name: configure aws cred using oidc
              uses: aws-actions/configure-aws-credentials@v6.2.3
              with:
                role-to-assume: ${{vars.AWS_TERRAFORM_PLAN_ROLE_ARN}}
                aws-region: ${{vars.AWS_REGION}}
            
            - name: verify aws identity
              run: aws sts get-caller-identity 
            
            - name: terraform plan 
              run: terraform plan -input=false -no-color

        

